//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrosheet_Persist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play_Bevent
    {
        public string game_id { get; set; }
        public string visiting_team_id { get; set; }
        public string inning { get; set; }
        public string batting_team_id { get; set; }
        public string outs { get; set; }
        public string count_balls { get; set; }
        public string count_strikes { get; set; }
        public string visiting_score { get; set; }
        public string home_score { get; set; }
        public string batter_player_id { get; set; }
        public string batter_bats { get; set; }
        public string pitcher_player_id { get; set; }
        public string pitcher_throws { get; set; }
        public string first_runner_player_id { get; set; }
        public string second_runner_player_id { get; set; }
        public string third_runner_player_id { get; set; }
        public string event_text { get; set; }
        public string leadoff_flag { get; set; }
        public string pinchhit_flag { get; set; }
        public string defensive_position { get; set; }
        public string lineup_position { get; set; }
        public string event_type { get; set; }
        public string batter_event_flag { get; set; }
        public string ab_flag { get; set; }
        public string hit_value { get; set; }
        public string sh_flag { get; set; }
        public string sf_flag { get; set; }
        public string outs_on_play { get; set; }
        public string RBI_on_play { get; set; }
        public string wild_pitch_flag { get; set; }
        public string passed_ball_flag { get; set; }
        public string fielded_by { get; set; }
        public string hit_location { get; set; }
        public string num_errors { get; set; }
        public string batter_dest { get; set; }
        public string first_runner_dest { get; set; }
        public string second_runner_dest { get; set; }
        public string third_runner_dest { get; set; }
        public string event_num { get; set; }
        public System.Guid record_id { get; set; }
    }
}
